# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.define "master" do |k3scluster|
      k3scluster.vm.hostname = "master.k3s"
      k3scluster.vm.network "private_network", ip: "192.168.33.10"
      k3scluster.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "k3s-master"
      end
      k3scluster.vm.provision "shell", inline: <<-SHELL
        yum -y install policycoreutils-python
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface eth1" sh -
        echo "PATH=/usr/local/bin:$PATH" >> /root/.bashrc 
      SHELL
  end

end